### ISSUE TITLE
实际上官方已经提供了docker镜像，通过配置文件即可开放端口以及web界面控制

### ISSUE THREAD

**Issue by ghost** [RedSTARO/singboxWebOnDocker#1]
其实也不能算是个问题，我自己也有时重复造轮子，其实这个项目挺好的，可是我还是想说，官方有轮子了，希望别生气。唉
镜像地址：https://sing-box.sagernet.org/installation/docker/
在配置文件中加入以下内容可以实现端口 control/7894 UI 控制，但是唯一的问题是，在代理启动的时候，控制界面访问超时

    {
      "experimental": {
        "clash_api": {
          "external_controller": ":7894",
          "external_ui": "ui",
          "secret": "",
          "external_ui_download_url": "https://mirror.ghproxy.com/https://github.com/MetaCubeX/Yacd-meta/archive/gh-pages.zip",
          "external_ui_download_detour": "direct",
          "default_mode": "rule"
        },
        "cache_file": {
          "enabled": true,
          "store_fakeip": false
        }
      }
    }
在配置中加入入站配置可以实现端口开放 http/https/7891 socks/7892 mixed/7893，并通过docker映射即可，

    {
       "inbounds": [
          {
            "type": "tun",
            "inet4_address": "172.19.0.1/30",
            "mtu": 9000,
            "auto_route": true,
            "strict_route": false,
            "sniff": true
          },
          {
            "type": "http",
            "listen": "0.0.0.0",
            "listen_port": 7891,
            "sniff": true,
            "users": []
          },
          {
            "type": "socks",
            "listen": "0.0.0.0",
            "listen_port": 7892,
            "sniff": true,
            "users": []
          },
          {
            "type": "mixed",
            "listen": "0.0.0.0",
            "listen_port": 7893,
            "sniff": true,
            "users": []
          }
        ]
    }
可是，说实话，json的配置看起来还是很复杂，yaml很直观，sing-box一直在更新配置方案，我却觉得自己有些跟不上了，如果是固定格式的话就好了，也不是特别想乱动配置文件的呀，😮‍💨

**Comment by RedSTARO** [comment]
谢谢提醒，在这个仓库开出来不久后经过群友提醒，已经改用https://github.com/juewuy/ShellCrash 了，咱当时写这个的初衷的能直接解析订阅链接生成配置文件给singbox用，不然singbox需要手动填写节点配置，实现方式也确实有些屎山了，总之还是谢谢提醒

**Comment by RedSTARO** [comment]
> 其实也不能算是个问题，我自己也有时重复造轮子，其实这个项目挺好的，可是我还是想说，官方有轮子了，希望别生气。唉 镜像地址：https://sing-box.sagernet.org/installation/docker/ 在配置文件中加入以下内容可以实现端口 control/7894 UI 控制，但是唯一的问题是，在代理启动的时候，控制界面访问超时
> 
> ```
> {
>   "experimental": {
>     "clash_api": {
>       "external_controller": ":7894",
>       "external_ui": "ui",
>       "secret": "",
>       "external_ui_download_url": "https://mirror.ghproxy.com/https://github.com/MetaCubeX/Yacd-meta/archive/gh-pages.zip",
>       "external_ui_download_detour": "direct",
>       "default_mode": "rule"
>     },
>     "cache_file": {
>       "enabled": true,
>       "store_fakeip": false
>     }
>   }
> }
> ```
> 
> 在配置中加入入站配置可以实现端口开放 http/https/7891 socks/7892 mixed/7893，并通过docker映射即可，
> 
> ```
> {
>    "inbounds": [
>       {
>         "type": "tun",
>         "inet4_address": "172.19.0.1/30",
>         "mtu": 9000,
>         "auto_route": true,
>         "strict_route": false,
>         "sniff": true
>       },
>       {
>         "type": "http",
>         "listen": "0.0.0.0",
>         "listen_port": 7891,
>         "sniff": true,
>         "users": []
>       },
>       {
>         "type": "socks",
>         "listen": "0.0.0.0",
>         "listen_port": 7892,
>         "sniff": true,
>         "users": []
>       },
>       {
>         "type": "mixed",
>         "listen": "0.0.0.0",
>         "listen_port": 7893,
>         "sniff": true,
>         "users": []
>       }
>     ]
> }
> ```
> 
> 可是，说实话，json的配置看起来还是很复杂，yaml很直观，sing-box一直在更新配置方案，我却觉得自己有些跟不上了，如果是固定格式的话就好了，也不是特别想乱动配置文件的呀，😮‍💨

btw,根据我之前的尝试，启动singbox时立即进入管理面板超时应该是因为没有下载好panel的zip包，稍等一会刷新或者手动放置就不会了。
稍晚我会存档此项目，谢谢您的关注。

**Comment by ghost** [comment]
> 谢谢提醒，在这个仓库开出来不久后经过群友提醒，已经改用https://github.com/juewuy/ShellCrash 了，咱当时写这个的初衷的能直接解析订阅链接生成配置文件给singbox用，不然singbox需要手动填写节点配置，实现方式也确实有些屎山了，总之还是谢谢提醒

好的，我去看看您推荐的项目
